# Generated by Django 2.1.1 on 2018-09-14 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
